apiVersion: v1
kind: Pod
metadata:
  name: good-limits
  namespace: default
spec:
  containers:
    - name: app
      image: ghcr.io/tmarktg/ato-in-a-pipeline:stable
      resources:
        limits:
          cpu: "250m"
          memory: "128Mi"
