apiVersion: v1
kind: Service
metadata:
  name: readiness-board
  labels:
    app: readiness-board
spec:
  selector:
    app: readiness-board
  ports:
    - name: http
      port: 8000
      targetPort: http
